title: 'DDP Transporte'
default_lang: de
author:
  name: 'DDP Transporte'
  email: info@ddp-transporte.ch
taxonomies:
  - category
  - tag
metadata:
  description: 'DDP Transporte vermietet Lieferwagen mit Hebebühne und hilft bei Umzügen und Entsorgungen.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
