title: 'DD Pasuljanovic Transporte'
default_lang: de
author:
  name: 'DD Pasuljanovic Transporte'
  email: info@ddp-transporte.ch
taxonomies:
  - category
  - tag
metadata:
  description: 'DD Pasuljanovic Transporte vermietet Lieferwagen mit Hebebühne und hilft bei Umzügen und Entsorgungen.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
