enabled: true
favicon:
  user/themes/mache/images/favicon.png:
    name: favicon.png
    type: image/png
    size: 1177
    path: user/themes/mache/images/favicon.png
left_footer: "&copy; 2015 COPYRIGHT MACHE TEMPLATE\r\n\r\nFree Template by FreeTemplates.pro\r\n"
right_footer: 'DESIGNED BY SYMU.CO'
blog_thumbnail_width: 600
blog_thumbnail_height: 450
default_background_image:
  user/themes/mache/images/favicon.png:
    name: favicon.png
    type: image/png
    size: 1177
    path: user/themes/mache/images/favicon.png
logo:
  user/themes/mache/images/_dd-pasuljanovic-transporte-logo.png:
    name: _dd-pasuljanovic-transporte-logo.png
    type: image/png
    size: 19027
    path: user/themes/mache/images/_dd-pasuljanovic-transporte-logo.png
